package lobos.andrew.science.chloroplast;

import lobos.andrew.science.AnswerField;
import lobos.andrew.science.BioTeachingTool;

/**
 *
 * @author andrew
 */
public class Chloroplast extends javax.swing.JFrame implements lobos.andrew.science.TeachingToolGUI {

    
    private AnswerField as_granum;
    private AnswerField as_thylakoids;
    private AnswerField as_stroma;
    private final BioTeachingTool parentWindow;
    
    public Chloroplast(BioTeachingTool parentWindow) {
        initComponents();
        as_granum = new AnswerField(granum, "granum", "A granum is one stack of thylakoids.", this);
        as_thylakoids = new AnswerField(thylakoid, "thylakoids", "Thylakoids use chlorophyll molecules on their surface to create sugars.", this);
        as_stroma = new AnswerField(stroma, "stroma", "The stroma is the area inside the chloroplast where reactions occue and sugars are created.", this);
        setLocationRelativeTo(null);
        setVisible(true);
        this.parentWindow = parentWindow;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        thylakoid = new javax.swing.JTextField();
        stroma = new javax.swing.JTextField();
        granum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoBox = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(thylakoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 100, -1));
        getContentPane().add(stroma, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 90, -1));
        getContentPane().add(granum, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lobos/andrew/science/chloroplast/chloroplastCartoon.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 250));

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        infoBox.setColumns(15);
        infoBox.setLineWrap(true);
        infoBox.setRows(5);
        jScrollPane1.setViewportView(infoBox);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        as_granum.reset();
        as_thylakoids.reset();
        as_stroma.reset();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField granum;
    private javax.swing.JTextArea infoBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField stroma;
    private javax.swing.JTextField thylakoid;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setHelpText(String str) {
        infoBox.setText(str);
    }
    
    @Override
    public void dispose()
    {
        parentWindow.setVisible(true);
        super.dispose();
    }
}
